version: '3.8'

services:
  dizoriza-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/results:/app/static/results
      - ./static/uploads:/app/static/uploads
    restart: always
